version: "3.8"
services:
  reactclient:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3008:3008"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
  mongodb:
    image: mongo
    container_name: mongo
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  mongodbdata:
  rabbitmqdata:
