name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  dotnet-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        working-directory: CodexHub
        run: dotnet restore ./CodexHub.sln
      - name: Build solution
        working-directory: CodexHub
        run: dotnet build --no-restore ./CodexHub.sln
      - name: Test solution
        working-directory: CodexHub
        run: dotnet test --no-build --verbosity normal ./CodexHub.sln
  react-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
        working-directory: frontend
      - run: npm run build --if-present
        working-directory: frontend
        env:
          CI: false
