name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        working-directory: CodexHub
        run: dotnet restore ./CodexHub.sln
      - name: Build books
        working-directory: CodexHub
        # working-directory: CodexHub/BookService
        run: dotnet build --no-restore ./CodexHub.sln
      - name: Test books
        working-directory: CodexHub
        # working-directory: CodexHub/BookService.Tests
        run: dotnet test --no-build --verbosity normal ./CodexHub.sln
